### PR TITLE
code reworks, bitHound fixes, attached eslint

### PR DESCRIPTION
**Pull request by Delagen**

### CODE REVIEW

**Comment by Delagen** [comment]
Don't merge it. It fails compatibility

**Comment by amitguptagwl** [comment]
@Delagen can you please provide more detail about the code changes, compatibility with browsers, IE check, performance check etc.?

**Comment by Delagen** [comment]
@amitguptagwl I simply make some code arrange and tries to solve lint issues bitHound found. I think to migrate to ES6+ codebase and make browser bundle using webpack or other bundler with transpilation )

**Comment by amitguptagwl** [comment]
Thanks @Delagen it is really helpful. Let me check changes separately for performance and browser compatibility before merging.

I tried ES6 migration a long time back, but it impacted performance so I reverted back my changes as it is limited to this project only. I'm not sure if I was doing anything wrong that time or if that degradation is still applicable on current code.

**Comment by Delagen** [comment]
@amitguptagwl Now it may be more working.
I make main lib/parser.js.
It works in older node.js but Travis install all dependencies and webpack cannot install due engine restriction.
Bundle after generation need some fix I specified in webpack.config.js.

**Comment by amitguptagwl** [comment]
Sorry for the late response, it's a festive season here. So I'm not getting the chance to check for performance and compatibility. will do it after Monday.

**Comment by amitguptagwl** [comment]
I've just run perf tests. It seems there is not impact due to this merge

**Comment by amitguptagwl** [comment]
This observation may or may not impact. Need to check it

```js
this.attrsMap = {}; // in xmlNode.js may break nimn parsing.
```

webpack should generate beautify file instead of minified as CDN is already taking care of that, or both minified and normal.

**Comment by Delagen** [comment]
@amitguptagwl mode: production enabled minify by default.

**Comment by Delagen** [comment]
@amitguptagwl I merged master but fails latest undefined check ((

**Comment by amitguptagwl** [comment]
I have also resolved conflicts in my local for your merge. But somehow not able to push the changes. :(

**Comment by Delagen** [comment]
Resolved error )

**Comment by amitguptagwl** [comment]
Thanks @Delagen . I should have kept patience.

**Comment by Delagen** [comment]
squashed history )

**Comment by amitguptagwl** [comment]
:)

@Delagen  any benefit of

* removing LICENSE file?
* in package.json, pointing `main` to generated file instead of src/parser.js

**Comment by Delagen** [comment]
@amitguptagwl  Sorry). Restored LICENSE
main pointed to generated to support old version of Node.JS and browsers )
I removed testing from travis versions older than 6 cause it fail only for cannot install webpack due engine. But must work when from NPM

**Comment by amitguptagwl** [comment]
Hmm, thanks. Can it impact the way it includes in other npm packages? I hope you must have already tested it. But just wanted to double check.

**Comment by Delagen** [comment]
@amitguptagwl It's must works. But I didn't make deep tests. It must works also on IE 9 and later.
On IE7+ works with a little polyfill for defineProperty

**Pull request merged**
