### PR TITLE
remove unneded nimnjs dependency, move opencollective to devDependenc…

### PR DESCRIPTION
**Pull request by Delagen**
…ies and replace it with more light opencollective-postinstall

### CODE REVIEW

**Comment by Delagen** [comment]
What do you think @amitguptagwl ?
opencollective ~14Mb, ~3500 files which is unneded in production
opencollective-postinstall ~4Mb, but I think too large also

**Comment by amitguptagwl** [comment]
Agree. However, I'm keeping the nimnjs as I'm doing some experiments which will be released soon

**Comment by amitguptagwl** [comment]
@Delagen How did you figure out the size of opencollective?

```
du -hs node_modules/opencollective/
648K	node_modules/opencollective/

```

I even checked the size of `node_modules` before and after this patch. There is not much change in the size. 

Moreover opencollective-postinstall is giving error at the time of installation while opencolletive is working fine.

**Comment by Delagen** [comment]
@amitguptagwl Install it in separate clean project. It does not big itself, but take a lot dependencies

**Comment by Delagen** [comment]
small patch
```
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- package.json	(revision 5dfa8cdcd7d7eed47b39ee9ac4dc65e50cd11d43)
+++ package.json	(date 1519893974848)
@@ -9,7 +9,7 @@
     "bundle": "browserify src/parser.js -s parser > lib/parser.js",
     "coverage": "node ./benchmark/perfTest.js; istanbul cover -x \"spec/*spec.js\" jasmine spec/*spec.js;",
     "coverage:check": "istanbul check-coverage --branch 90 --statement 90",
-    "postinstall": "opencollective-postinstall || exit 0"
+    "postinstall": "opencollective postinstall || exit 0"
   },
   "bin": {
     "xml2js": "cli.js"
@@ -69,7 +69,7 @@
     "http-server": "^0.11.1",
     "istanbul": "^0.4.5",
     "jasmine": "^3.0.0",
-    "opencollective-postinstall": "^1.1.1",
+    "opencollective": "^1.0.3",
     "portfinder": "^1.0.13",
     "xml2js": "^0.4.19",
     "zombie": "^5.0.8"

```

**Comment by amitguptagwl** [comment]
@Delagen 
1. apologies, I had to revert old commit as I had to fix and release #59.
2. I checked with empty repo and I agree that there is a huge difference.
3. Your suggestion to move it under devDependencies is a better approach.

I'll apply it manually and will publish along with the fix of #60 (if it is not invalid)

**Pull request merged**
