### PR TITLE
Validator: Fail for stray ampersand characters

### LINKED ISSUE #214: Validation of unescaped ampersand
### Checklist
* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Input
"<a>x & y</a>"

### Code
```js
xmlParser.validate("<a>x & y</a>")
```
### Output
true (valid XML)

### Expected output
false (invalid XML)

**Would you like to work on this issue?**
- [ ] Yes
- [x] No (sorry...)

## Details
I'm trying to validate a given input string, to check if it is a valid XML.
I've found that if a text node contains an unescaped ampersand, the xmlparser validate it as valid although other XML parser libraries treat it as invalid.

I also tried using the tagValueProcessor parameter as appears in the examples, but the "he" package also treats the ampersand as valid (I guess that in HTML unambiguous ampersands are valid).

Also note that the output is the same regardless of the spaces around the ampersand (i.e., even if the ampersand is ambiguous).

### PR DESCRIPTION
**Pull request by orgads**
Fixes #214

# Type
* [X]Bug Fix
* [ ]Refactoring / Technology upgrade
* [ ]New Feature

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Thanks for your PR @orgads 

I can see that after this PR we'll be doing 3 more checks per character in the given data which will impact the performance. Hence, I'm looking for options to minimize it. Eg when we find `&` we can check if the consecutive letters are word letter until we find `;`. if this sequence is not found we can throw an error. It'll save 2 comparisons per character.

Let me know your opinion on this.

**Comment by orgads** [comment]
Done, but I still need to add some unit tests.

**Comment by amitguptagwl** [comment]
@orgads Let me know once you're done.

**Comment by orgads** [comment]
I'm done

**Comment by amitguptagwl** [comment]
Thanks for the effort you spent.

**Comment by orgads** [comment]
You're welcome. What about my other PR?

**Comment by amitguptagwl** [comment]
That PR needs more time to review. As I'm out of the station for 1 more week, I'm not able to finish it. Will do it hopefull by 5th Jan.

**Comment by orgads** [comment]
Sure, take your time :)

**Pull request merged**
