### PR TITLE
CLI Tools fixes, part 2

### PR DESCRIPTION
**Pull request by KurtPreston**
# Purpose / Goal
Yesterday, I submitted a PR updating the `package.json` to include some files missing to get the CLI working.  Running the updated code today, I realized there were some other issues, some of which prevented install.  This addresses them.

Apologies for not catching these issues yesterday.

There are some other enhancements I may submit to the CLI tools later, but I first wanted to make sure to fix the issues I created.

# Type
[x]Bug Fix
[ ]Refactoring / Technology upgrade
[ ]New Feature

### CODE REVIEW

**Comment by SameerSiddiqui** [comment]
When this is going in ?

**Comment by SameerSiddiqui** [comment]
npm install --no-progress --no-optional --ignore-scripts --no-shrinkwrap

Doesn't work...

**Comment by KurtPreston** [comment]
@SameerSiddiqui until this gets merged, I'd suggest using the previous release `3.12.0`

**Comment by amitguptagwl** [comment]
@KurtPreston Thanks for the immediate action. 

published

**Pull request merged**
