### PR TITLE
Correctly remove CRLF line breaks

### PR DESCRIPTION
**Pull request by j0k3r**
Related to https://github.com/NaturalIntelligence/fast-xml-parser/issues/36

In fact, the XML I retrieve from an external API has CRLF line break instead of just LF.
Your regex doesn't handle that case that's why the validator always return `false` (see https://stackoverflow.com/a/10805198/569101)

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Thanks for the changes and tests. I completely agree that I didn't consider '\r' in my regex.

**Comment by Delagen** [comment]
@amitguptagwl Any plan to update NPM?

**Comment by amitguptagwl** [comment]
:) I was actually busy with some other project. But I'll publish it tomorrow morning sure.

**Comment by Delagen** [comment]
@amitguptagwl Thanks. Temporary use git version )) Also reach this issue when parse SOAP responses from windows service )

**Comment by amitguptagwl** [comment]
Done. published :)

**Pull request merged**
